spring:
  application:
    name: patient-api
  lifecycle:
    timeout-per-shutdown-phase: 15s

server:
  shutdown: graceful

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS:3600000}

dynamodb:
  table:
    patients: patients
    users: users

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enabled: true
  api-docs:
    path: /v3/api-docs